=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Envia/Unidade de Medida/XSD/EcalcIntegraEAI_UNIDADE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="MODUNIDADE">
    <xsd:annotation>
      <xsd:documentation>Modelo de dados para integração</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="UNIDADE">
          <xsd:annotation>
            <xsd:documentation>Integração de unidade de medida</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="ID" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> ID do registro </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="20"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="NOME" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Nome abreviado da unidade. Ex.: Kg, Und, Ton</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="10"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="DESCRICAO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Descrição da unidade. Ex.: Kilo, Unidade, Tonelada </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="60"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="ATIVO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Status do registro: 'T' ou 'F' </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="OPERADOR" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Operador: 1 = Multiplicador; 2 = Divisor. (Padrão = Multiplicador) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="MULTIPLICADOR" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Valor do multiplicador da unidade. (Padrão = 1.00)  </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" default="0">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:pattern value="0|0\.[0-9]{1,2}|[0-9]{0,12}(\.[0-9]{1,2})?" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:all>
            <xsd:attribute name="OPERACAOINTEGRACAO" use="optional">
              <xsd:annotation>
                <xsd:documentation>Tipo da Operação. Inclusão ou Edição: 0 ou Sem Atributo; Exclusão: 1</xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>  
</xsd:schema>

=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Desenvolvidos/Unidade de Medida/XSD/EcalcIntegraEAI_UNIDADE.xml
<?xml version="1.0" encoding="UTF-8"?>
<MODUNIDADE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EcalcIntegraEAI_UNIDADE.xsd">
  <UNIDADE>
    <ID>
      <value>value</value>
    </ID>
    <NOME>
      <value>value</value>
    </NOME>
    <DESCRICAO>
      <value>value</value>
    </DESCRICAO>
    <ATIVO>
      <value>value</value>
    </ATIVO>
    <OPERADOR>
      <value>value</value>
    </OPERADOR>
    <MULTIPLICADOR>
      <value>0</value>
    </MULTIPLICADOR>
  </UNIDADE>
</MODUNIDADE>
