=== eltonteodoro1308/IMESP/Fontes/Ecalc/XSD´s/Recursos (Operadores - Máquinas)/mpschemas.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"><xsd:include schemaLocation="MT610OK.xsd"/><xsd:element name="TOTVSIntegrator" id="A01"><xsd:annotation><xsd:documentation>TAG de grupo das informações da transação de integração</xsd:documentation></xsd:annotation><xsd:complexType><xsd:all><xsd:element name="GlobalProduct" id="A10"><xsd:annotation><xsd:documentation>Descricao:Produto</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="20"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="GlobalFunctionCode" id="A13"><xsd:annotation><xsd:documentation>Descricao:Produto que colocou a mensagem na fila</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="20"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="GlobalDocumentFunctionCode" id="A02"><xsd:annotation><xsd:documentation>Descricao:Nome da transação globalOBS:Código da transação para identificação do layout e de que tipo de dados serão integrados.</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="20"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="GlobalDocumentFunctionDescription" id="A03"><xsd:annotation><xsd:documentation>Descricao:Descrição da transação globalOBS:Descrição sucinta da transação. Será utilizada no monitor de transações do adapter.</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="60"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="DocVersion" id="A04" minOccurs="1"><xsd:annotation><xsd:documentation>Descricao:Versão do layout da transaçãoOBS:Exemplo: T1.00</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="4"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="DocDateTime" id="A05"><xsd:annotation><xsd:documentation>Descricao:Data e hora da transaçãoOBS:Formato AAAA-MM-DDTHH:MM:SSZ</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"/></xsd:simpleType></xsd:element><xsd:element name="DocIdentifier" id="A06"><xsd:annotation><xsd:documentation>Descricao:Id da transação no formato UUID b39319e0-2466-4f6f-9381-c2cb9c1498a3OBS:Código único de identificação da transação. Pode ser utilizada pela rotina processadora.</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="36"/><xsd:minLength value="36"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="DocCompany" id="A07"><xsd:annotation><xsd:documentation>Descricao:Id da EmpresaOBS:Identificação da empresa geradora da informação</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="10"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="DocBranch" id="A08"><xsd:annotation><xsd:documentation>Descricao:Id da FilialOBS:Identificação da filial geradora da informação</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="10"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="DocName" id="A12"><xsd:annotation><xsd:documentation>Descricao:Nome do cliente</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="20"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="DocFederalID" id="A11"><xsd:annotation><xsd:documentation>Descricao:Id do cliente (CPF, CNPJ e etc)</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="20"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="DocType" id="A09"><xsd:annotation><xsd:documentation>Descricao:Tipo de processamentoOBS:1-Síncrono2-Assíncrono</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="1"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="Message" id="B01"><xsd:annotation>                      <xsd:documentation>Descricao:Tag da mensagem de transação</xsd:documentation></xsd:annotation><xsd:complexType><xsd:sequence><xsd:element name="Layouts" maxOccurs="unbounded" id="B02" minOccurs="1"><xsd:annotation><xsd:documentation>Descricao: Tag de transaçãoObs: Todas as transações incluídas nesta tag deverão ser processadas em conjunto com se fosse uma única transação.</xsd:documentation></xsd:annotation><xsd:complexType><xsd:all><xsd:element name="Version" id="B03"><xsd:annotation><xsd:documentation>Descricao: Versão da transaçãoObs: Exemplo: T1.00</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="4"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="Identifier" id="B04"><xsd:annotation><xsd:documentation>Descricao: Id da transação unitária no formato UUID b39319e0-2466-4f6f-9381-c2cb9c1498a3</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="10"/><xsd:minLength value="10"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="FunctionCode" id="B05"><xsd:annotation><xsd:documentation>Descricao: Nome da função a ser executada pelo EAI no momento da entregada mensagem para o adapter correspondente.</xsd:documentation></xsd:annotation><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="20"/><xsd:minLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element><xsd:element name="Content" id="B10"><xsd:annotation><xsd:documentation>Descricao: Tag da transação unitária</xsd:documentation></xsd:annotation><xsd:complexType><xsd:choice maxOccurs="1"><xsd:element ref="MT610OK" maxOccurs="1"/></xsd:choice></xsd:complexType></xsd:element></xsd:all></xsd:complexType></xsd:element></xsd:sequence></xsd:complexType></xsd:element></xsd:all></xsd:complexType></xsd:element></xsd:schema>

=== eltonteodoro1308/IMESP/EAI/MATA030/mpschemas.xml
<?xml version="1.0" encoding="UTF-8"?>
<TOTVSIntegrator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mpschemas.xsd">
  <GlobalProduct>GlobalProduct</GlobalProduct>
  <GlobalFunctionCode>GlobalFunctionCode</GlobalFunctionCode>
  <GlobalDocumentFunctionCode>GlobalDocumentFunctionCode</GlobalDocumentFunctionCode>
  <GlobalDocumentFunctionDescription>GlobalDocumentFunctionDescription</GlobalDocumentFunctionDescription>
  <DocVersion>DocVersion</DocVersion>
  <DocDateTime>DocDateTime</DocDateTime>
  <DocIdentifier>DocIdentifier</DocIdentifier>
  <DocCompany>DocCompany</DocCompany>
  <DocBranch>DocBranch</DocBranch>
  <DocName>DocName</DocName>
  <DocFederalID>DocFederalID</DocFederalID>
  <DocType>DocType</DocType>
  <Message>
    <Layouts>
      <Version>Version</Version>
      <Identifier>Identifier</Identifier>
      <FunctionCode>FunctionCode</FunctionCode>
      <Content>
        <MATA030/>
      </Content>
    </Layouts>
  </Message>
</TOTVSIntegrator>
