=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Envia/Produto Acabado/XSD/EcalcIntegraEAI_ITEMESTOQUE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="MODITEMESTOQUE">
    <xsd:annotation>
      <xsd:documentation>Modelo de dados para integração</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ITEMESTOQUE">
          <xsd:annotation>
            <xsd:documentation>Integração de item de estoque</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="ID" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> ID do registro </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="20"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>              
              <xsd:element name="NOME" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Nome do item de estoque </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="60"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="DESCRICAO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Descrição do item de estoque </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="120"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>              
              <xsd:element name="ATIVO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Status do registro: 'T' ou 'F' </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="CODCLIENTE" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> (APENAS PRODUTOS / ITEMPROD = 2) Código do cliente do produto </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="15"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="ITEMPROD" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Tipo do Item: 1 = Matéria-Prima; 2 = Produto </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            <xsd:element name="TIPOITEMEC" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> (APENAS MATERIA-PRIMA / ITEMPROD = 1) Tipo do Item: 0 = Chapa; 1 = Papel; 2 = Tinta; 3 = Outros </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            <xsd:element name="PAPELFAMILIA" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> (APENAS MATERIA-PRIMA (ITEMPROD = 1) E PAPEL (TIPOITEMEC = 1)) Código da familia do do papel </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="12"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            <xsd:element name="PAPELGRAMATURA" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> (APENAS MATERIA-PRIMA (ITEMPROD = 1) E PAPEL (TIPOITEMEC = 1)) Gramatura do papel </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:int">
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            <xsd:element name="PAPELLARGURA" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> (APENAS MATERIA-PRIMA (ITEMPROD = 1) E PAPEL (TIPOITEMEC = 1)) Largura do papel </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" default="0">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:pattern value="0|0\.[0-9]{1,2}|[0-9]{0,12}(\.[0-9]{1,2})?" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="PAPELALTURA" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> (APENAS MATERIA-PRIMA (ITEMPROD = 1) E PAPEL (TIPOITEMEC = 1)) Altura do papel </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" default="0">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:pattern value="0|0\.[0-9]{1,2}|[0-9]{0,12}(\.[0-9]{1,2})?" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:all>
            <xsd:attribute name="OPERACAOINTEGRACAO" use="optional">
              <xsd:annotation>
                <xsd:documentation>Tipo da Operação. Inclusão ou Edição: 0 ou Sem Atributo; Exclusão: 1</xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>  
</xsd:schema>

=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Envia/Produto Acabado/XSD/EcalcIntegraEAI_ITEMESTOQUE.xml
<?xml version="1.0" encoding="UTF-8"?>
<MODITEMESTOQUE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EcalcIntegraEAI_ITEMESTOQUE.xsd">
  <ITEMESTOQUE OPERACAOINTEGRACAO="">
    <ID>
      <value>value</value>
    </ID>
    <NOME>
      <value>value</value>
    </NOME>
    <DESCRICAO>
      <value>value</value>
    </DESCRICAO>
    <ATIVO>
      <value>value</value>
    </ATIVO>
    <CODCLIENTE>
      <value>value</value>
    </CODCLIENTE>
    <ITEMPROD>
      <value>value</value>
    </ITEMPROD>
    <TIPOITEMEC>
      <value>value</value>
    </TIPOITEMEC>
    <PAPELFAMILIA>
      <value>value</value>
    </PAPELFAMILIA>
    <PAPELGRAMATURA>
      <value>0</value>
    </PAPELGRAMATURA>
    <PAPELLARGURA>
      <value>0</value>
    </PAPELLARGURA>
    <PAPELALTURA>
      <value>0</value>
    </PAPELALTURA>
  </ITEMESTOQUE>
</MODITEMESTOQUE>
