=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Envia/Requisicoes Devolucoes/XSD/EcalcIntegraEAI_MOVIMENTACAOOS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="MODMOVIMENTACAOOS">
    <xsd:annotation>
      <xsd:documentation>Modelo de dados para integração</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="MOVIMENTACAOOS">
          <xsd:annotation>
            <xsd:documentation>Integração de movimentações utilizadas em relatório de cotejo e metas </xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="ID" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> ID do registro </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="20"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="NUMANO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Número da ordem de serviço Ecalc </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="20"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="CODITEM" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Código da matéria-prima (usando para requisição ou devolução) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="30"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="DESCRICAO" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Descrição da matéria-prima (usando para requisição ou devolução) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="150"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="TIPO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Tipo do movimento: Requisicao = 1; Devolucao = 2; Servico Terceiro = 3 </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="DATAMOVIMENTO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Data do registro. Formato: AAAA-MM-DDTHH:MM:SSZ (Ex.: 2017-05-10T21:07:04Z) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="40"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="QUANTIDADE" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Quantidade da movimentação </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" default="0">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:pattern value="0|0\.[0-9]{1,2}|[0-9]{0,12}(\.[0-9]{1,2})?" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="VALORTOTAL" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Valor total movimentação </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" default="0">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:pattern value="0|0\.[0-9]{1,2}|[0-9]{0,12}(\.[0-9]{1,2})?" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="VALORICMS" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Valor do icms da movimentação </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" default="0">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:pattern value="0|0\.[0-9]{1,2}|[0-9]{0,12}(\.[0-9]{1,2})?" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="STATUS" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Status do movimento: Efetivada = 1, Cancelada = 2 </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:all>
            <xsd:attribute name="OPERACAOINTEGRACAO" use="optional">
              <xsd:annotation>
                <xsd:documentation>Tipo da Operação. Inclusão ou Edição: 0 ou Sem Atributo; Exclusão: 1</xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>  
</xsd:schema>

=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Desenvolvidos/Requisicoes Devolucoes/XSD/EcalcIntegraEAI_MOVIMENTACAOOS.xml
<?xml version="1.0" encoding="UTF-8"?>
<MODMOVIMENTACAOOS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EcalcIntegraEAI_MOVIMENTACAOOS.xsd">
  <MOVIMENTACAOOS>
    <ID>
      <value>value</value>
      <!--  NÃ£o pode repetir -->
    </ID>
    <NUMANO>
      <value>value</value>
      <!--  Pode repetir -->
    </NUMANO>
    <TIPO>
      <value>value</value>
    </TIPO>
    <DATAMOVIMENTO>
      <value>value</value>
    </DATAMOVIMENTO>
    <QUANTIDADE>
      <value>0</value>
    </QUANTIDADE>
    <VALORTOTAL>
      <value>0</value>
    </VALORTOTAL>
    <VALORICMS>
      <value>0</value>
    </VALORICMS>
    <STATUS>
      <value>value</value>
    </STATUS>
  </MOVIMENTACAOOS>
</MODMOVIMENTACAOOS>

=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Envia/Requisicoes Devolucoes/XSD/EcalcIntegraEAI_MOVIMENTACAOOS.xml
<?xml version="1.0" encoding="UTF-8"?>
<MODMOVIMENTACAOOS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EcalcIntegraEAI_MOVIMENTACAOOS.xsd">
  <MOVIMENTACAOOS OPERACAOINTEGRACAO="">
    <ID>
      <value>value</value>
    </ID>
    <NUMANO>
      <value>value</value>
    </NUMANO>
    <CODITEM>
      <value>value</value>
    </CODITEM>
    <DESCRICAO>
      <value>value</value>
    </DESCRICAO>
    <TIPO>
      <value>value</value>
    </TIPO>
    <DATAMOVIMENTO>
      <value>value</value>
    </DATAMOVIMENTO>
    <QUANTIDADE>
      <value>0</value>
    </QUANTIDADE>
    <VALORTOTAL>
      <value>0</value>
    </VALORTOTAL>
    <VALORICMS>
      <value>0</value>
    </VALORICMS>
    <STATUS>
      <value>value</value>
    </STATUS>
  </MOVIMENTACAOOS>
</MODMOVIMENTACAOOS>
