=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Envia/Recursos/XSD/EcalcIntegraEAI_MAQUINA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="MODMAQUINA">
    <xsd:annotation>
      <xsd:documentation>Modelo de dados para integração</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="MAQUINA">
          <xsd:annotation>
            <xsd:documentation>Integração de máquinas de impressão e acabamentos</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="ID" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> ID do registro </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="20"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="NOME" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Nome da máquina </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="60"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>              
              <xsd:element name="ATIVO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Status do registro: 'T' ou 'F' </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>              
              <xsd:element name="CUSTOHORA" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Custo hora da máquina </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" default="0">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:pattern value="0|0\.[0-9]{1,2}|[0-9]{0,12}(\.[0-9]{1,2})?" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="MEDIAPRODUTIVIDADE" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Média de produtividade da máquina </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" default="0">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:pattern value="0|0\.[0-9]{1,2}|[0-9]{0,12}(\.[0-9]{1,2})?" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:all>
            <xsd:attribute name="OPERACAOINTEGRACAO" use="optional">
              <xsd:annotation>
                <xsd:documentation>Tipo da Operação. Inclusão ou Edição: 0 ou Sem Atributo; Exclusão: 1</xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>  
</xsd:schema>

=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Envia/Recursos/XSD/EcalcIntegraEAI_MAQUINA.xml
<?xml version="1.0" encoding="UTF-8"?>
<MODMAQUINA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EcalcIntegraEAI_MAQUINA.xsd">
  <MAQUINA OPERACAOINTEGRACAO="">
    <ID>
      <value>value</value>
    </ID>
    <NOME>
      <value>value</value>
    </NOME>
    <ATIVO>
      <value>value</value>
    </ATIVO>
    <CUSTOHORA>
      <value>0</value>
    </CUSTOHORA>
    <MEDIAPRODUTIVIDADE>
      <value>0</value>
    </MEDIAPRODUTIVIDADE>
  </MAQUINA>
</MODMAQUINA>
