=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Envia/Transportadora/XSD/EcalcIntegraEAI_TRANSPORTADORA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="MODTRANSPORTADORA">
    <xsd:annotation>
      <xsd:documentation>Modelo de dados para integração</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="TRANSPORTADORA">
          <xsd:annotation>
            <xsd:documentation>Integração de transportadora</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="ID" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> ID do registro </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="20"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="NOME" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Nome </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="50"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="RAZAOSOCIAL" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Razão social </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="60"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="ATIVO" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Status do registro: 'T' ou 'F' </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="1"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="CPF" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> CPF (Apenas números) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="19"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="CNPJ" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> CNPJ (Apenas números) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="19"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="INSCRICAOMUNICIPAL" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Incrição municipal (Apenas números) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="15"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="INSCRICAOESTADUAL" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Incrição estadual (Apenas números) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="15"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="ENDERECO" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Endereço (logradouro + número) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="120"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="BAIRRO" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Bairro </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="40"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="CODMUNICIPIOIBGE" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Código IBGE do município </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="30"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="ESTADO" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> UF / Estado </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="2"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="CEP" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> CEP (Apenas números) </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="10"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="DDD" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> DDD </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="3"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>                    
                  </xsd:sequence>                  
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="TELEFONE" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Telefone </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="30"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="FAX" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> Fax </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="40"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>                    
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="EMAIL" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation> E-mail </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="1"/>
                          <xsd:maxLength value="250"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>              
            </xsd:all>
            <xsd:attribute name="OPERACAOINTEGRACAO" use="optional">
              <xsd:annotation>
                <xsd:documentation>Tipo da Operação. Inclusão ou Edição: 0 ou Sem Atributo; Exclusão: 1</xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>  
</xsd:schema>

=== eltonteodoro1308/IMESP/Fontes/Ecalc/fontes/Desenvolvidos/Transportadora/XSD/EcalcIntegraEAI_TRANSPORTADORA.xml
<?xml version="1.0" encoding="UTF-8"?>
<MODTRANSPORTADORA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EcalcIntegraEAI_TRANSPORTADORA.xsd">
  <TRANSPORTADORA>
    <ID>
      <value>value</value>
    </ID>
    <NOME>
      <value>value</value>
    </NOME>
    <RAZAOSOCIAL>
      <value>value</value>
    </RAZAOSOCIAL>
    <ATIVO>
      <value>value</value>
    </ATIVO>
  </TRANSPORTADORA>
</MODTRANSPORTADORA>
